version: '3.1'

services:
  mongodb:
    container_name: mongodb-toptal
    image: flqw/docker-mongo-local-replicaset
    ports:
      - 27001:27001 # mongo 1
      - 27002:27002 # mongo 2
      - 27003:27003 # mongo 3
  